import { ImageSourcePropType } from "react-native";

export const BG_STICKERS: ImageSourcePropType[] = [
  require("../assets/bg stickers/sticker_01.webp"),
  require("../assets/bg stickers/sticker_02.webp"),
  require("../assets/bg stickers/sticker_03.webp"),
  require("../assets/bg stickers/sticker_04.webp"),
  // require("../assets/bg stickers/sticker_05.webp"),
  require("../assets/bg stickers/sticker_06.webp"),
  // require("../assets/bg stickers/sticker_07.webp"),
  require("../assets/bg stickers/sticker_08.webp"),
  require("../assets/bg stickers/sticker_09.webp"),
  require("../assets/bg stickers/sticker_10.webp"),
  require("../assets/bg stickers/sticker_11.webp"),
  require("../assets/bg stickers/sticker_12.webp"),
  require("../assets/bg stickers/sticker_13.webp"),
  require("../assets/bg stickers/sticker_14.webp"),
  require("../assets/bg stickers/sticker_15.webp"),
  require("../assets/bg stickers/sticker_16.webp"),
  require("../assets/bg stickers/sticker_17.webp"),
  // require("../assets/bg stickers/sticker_18.webp"),
  require("../assets/bg stickers/sticker_19.webp"),
  require("../assets/bg stickers/sticker_20.webp"),
  require("../assets/bg stickers/sticker_21.webp"),
  require("../assets/bg stickers/sticker_22.webp"),
  require("../assets/bg stickers/sticker_23.webp"),
  require("../assets/bg stickers/sticker_24.webp"),
  require("../assets/bg stickers/sticker_25.webp"),
  require("../assets/bg stickers/sticker_26.webp"),
  require("../assets/bg stickers/sticker_27.webp"),
  require("../assets/bg stickers/sticker_28.webp"),
];
